import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";

const geistSans = {
  variable: "font-sans",
};

const geistMono = {
  variable: "font-mono",
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        {/* Telegram WebApp */}
        <Script src="https://telegram.org/js/telegram-web-app.js" />

        <Script id="telegram-user">
          {`
            if (window.Telegram?.WebApp) {
              const tg = window.Telegram.WebApp;

              tg.expand();

              const userId =
                tg.initDataUnsafe?.user?.id;

              if (userId) {
                localStorage.setItem(
                  "telegram_user_id",
                  userId.toString()
                );
              }
            }
          `}
        </Script>

        {children}
      </body>
    </html>
  );
}