import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";

const geistSans = {
  variable: "font-sans",
};

const geistMono = {
  variable: "font-mono",
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        {/* Telegram WebApp */}
        <Script src="https://telegram.org/js/telegram-web-app.js" />

        <Script id="telegram-user">
          {`
            if (window.Telegram?.WebApp) {
              const tg = window.Telegram.WebApp;

              tg.expand();

              const user = tg.initDataUnsafe?.user;

              if (user && user.id) {
                localStorage.setItem(
                  "telegram_user_id",
                  user.id.toString()
                );

                fetch("/api/sync-user", {
                  method: "POST",
                  headers: {
                    "Content-Type": "application/json",
                  },
                  body: JSON.stringify({
                    id: user.id,
                    first_name: user.first_name || "Telegram User",
                    username: user.username || ""
                  }),
                }).catch(function(err) {
                  console.error("Failed to sync user:", err);
                });
              }
            }
          `}
        </Script>

        {children}
      </body>
    </html>
  );
}